### ISSUE TITLE
Strange shapes on Edge

### ISSUE THREAD

**Issue by hrturlakov** [noppa/text-security#12]
There are displayed strange shapes when using `text-security-disc` only on Edge.
Is there a possible fix of this behavior?
![Capture](https://user-images.githubusercontent.com/6098190/84806937-c636e480-b006-11ea-9c51-0b62c2f56806.PNG)

**Comment by allenhwkim** [comment]
`type="password"` is used?

**Comment by hrturlakov** [comment]
No, `type="number"`. Strange thing is it's working pretty well with other two shapes.

**Comment by allenhwkim** [comment]
![image](https://user-images.githubusercontent.com/1437734/86820114-9f445f00-c056-11ea-9edf-58968a0c57b9.png)

I tested with Mac Microsoft Edge, which is Chronium-based, and it works fine. Maybe using old one?
https://support.microsoft.com/en-ca/help/4501095/download-the-new-microsoft-edge-based-on-chromium

**Comment by hrturlakov** [comment]
It happened on Microsoft Edge on WIndows. The version was one of the latest.

**Comment by superjanicko** [comment]
There is no problem in chromium based Edge browser, but only in "older" - EdgeHTML engine based version. (IE11 is fine, too)

**Comment by noppa** [comment]
Are you using a placeholder attribute with the password field? Could this be related to #3 and #5 where the cause was that Edge/IE also applied the font to the placeholder?

**Comment by superjanicko** [comment]
Thank you for your response. It doesnt belong to issues you mentioned...

When i changed font-family on body of https://noppa.github.io/text-security.html this happend:
![screen_EdgeHTML](https://user-images.githubusercontent.com/5222647/88169053-aef9a100-cc1b-11ea-9e20-e2dc8da19f0a.png)

**Comment by noppa** [comment]
Thanks. That's interesting... I'll try to repro this in a few days.  
Can you check the console's network tab and see what font it's actually loading? Maybe _if_ it's loading the non-compat version, we could try forcing the compatibility version and see if it works better.

**Comment by superjanicko** [comment]
Hi, I tried to switch to  '-compat.woff2' and it WORKS!!! Problem solved. Thank you
![screen_EdgeHTML-compat](https://user-images.githubusercontent.com/5222647/88253650-ef582e00-ccb2-11ea-8a44-6744730b6931.png)

**Comment by noppa** [comment]
Great, thanks for checking.  
Although that's also a bit disappointing because that means the optimized version now has issues both in Safari (#10) and in IE/Edge :sweat:  
I'll update the README to reflect that and might need to change the defaults to load the compat font

**Comment by superjanicko** [comment]
> optimized version now has issues

You have to look at it from the other side => If optimized version meets specification, **Safari and IE/Edge have a problem**
Good luck

**Comment by noppa** [comment]
Version 3.2 release candidate (installable with `npm i text-security@next`) has css files that should load the compatibility version of the font in IE and old non-chromium versions of Edge, so I think this is resolved with that. I'll bump that to new 3.2 version when I get a chance to test that things work as expected on iOS/OSX.
