### ISSUE TITLE
Firefox "rejected by sanitizer"

### ISSUE THREAD

**Issue by ygreenfield** [noppa/text-security#14]
Hi,

I just found your project as a solution to not having the browser remember the password field. Unfortunately, Firefox won't download the custom fonts. According to the Inspector, they're "rejected by sanitizer."

Is that something that's easy enough to fix?

Thank you!
Rob

**Comment by noppa** [comment]
Thanks for the report. What operating system & Firefox version are you on?  
Could you try with the compatibility version of the font? Open text-security.css and replace `text-security-disc.woff2` with `text-security-disc-compat.woff2`.

**Comment by ygreenfield** [comment]
Thanks for getting backto me :)
 
Both machines are Windows 10.
 
One is FF 77.0.1 and the other is FF 86.0.
 
Actually, now that I'm rereading the README, I see you want this installed
using npm. I don't have node or npm on the server. I simply downloaded the
files from the dist folder in git. Is that my problem?
 
(And there's no compatibity version in the folder, either).
 
Thanks again!
 
 


  _____

**Comment by noppa** [comment]
The dist folder actually contains files for older version 1 that I only keep around for backwards compatibility reasons. The guide in this repo used to say that people could just point to the dist folder's files through rawgit, so now I'm sort of stuck with keeping the files in there or bunch of websites could break...

Anyway... it's still weird though that those font files would cause issues, even though they're old they should still work ok. You might want to double check that your app is referring to the files correctly and your server is responding with the actual files. One thing that could cause the error you describe is that if the paths to the fonts in html/css are a bit off and your server responds with 404 html file and then Firefox obviously doesn't want to parse that file as a font file.

Whether that's the issue or not, you should probably use the newer version and not the files in dist folder. You can download the files from [the release page](https://github.com/noppa/text-security/releases/tag/v3.1.0), or you could install them with npm to your local machine and just copy-and-paste from node_modules folder to your server.

**Comment by ygreenfield** [comment]
Again, thanks for being so helpful.
 
So it's still not working in Firefox, but I don't think it's the fault of
the files, although I don't understand what I'm seeing yet, so I'm not sure.
 
First problem is, I think, that my site is not https, and the fonts are on a
server that was. When I moved them to the same server, I'm now getting
"Cross-Origin Request Blocked. Reason: CORS Header
'Access-Control-Allow-Origin' missing"
 
I don't know what that means and I'll need to research, but I can't today or
tomorrow. If you recognize that and have a quick "Oh that's easy!" answer,
please tell me. Otherwise, I'll keep hacking away at it and let you know
what I come up with.
 
Thanks again!
 


  _____

**Comment by noppa** [comment]
Just based on this info I can't say I recognize, sorry.  
If you have some code in a github repo or if you can just paste some html/css you have in here and tell a little about your server setup (are you using e.g. IIS, asp.net, express.js, Apache, some CDN, etc) I could maybe take a look, but otherwise it's hard to tell. CORS issues usually come up when you do requests from one site to a server in _another_ domain, so it sounds quite weird to me that you get CORS errors after moving the files to the _same_ server as the other stuff.

**Comment by noppa** [comment]
I'm going to close this as it seems likely that this is not actually a bug in the library.  
If things turn around and it seems that the problem is indeed in the library, you can open a new issue.
If you need general help with setting things up, you can send me an email (it's in my profile). I'll respond if I have time.

**Comment by ygreenfield** [comment]
K, thank you.
 
I'm thinking it has something to do with my site not being https, and even
if it's not the issue, it's about time to do https anyway. So until I make
my site https, I've put this on hold, probably a couple of weeks. I'll let
you know if that solved the issue.
 
Take care, and thanks for your responsiveness.
 
Yosi
 


  _____
