### ISSUE TITLE
text-security font is rendering characters much too far apart in latest version of chrome and firefox

### ISSUE THREAD

**Issue by resims** [noppa/text-security#18]
This is pulled right off of the demo page in Chrome 90.0.4430.93
![image](https://user-images.githubusercontent.com/42554731/116554319-0aeb0780-a8c9-11eb-834c-9bbc0a683132.png)

This is pulled right from the demo page in Firefox 88.0
![image](https://user-images.githubusercontent.com/42554731/116554453-32da6b00-a8c9-11eb-8aae-f03084999e21.png)

As you can see, for whatever reason, the dots are being rendered too far apart. This will cause issues when trying to determine how many characters you have typed thus far.

**Comment by resims** [comment]
In my project, I also verified that I updated to the latest version of your repo, and even so, I am still seeing this issue.

**Comment by resims** [comment]
I've done more research and discovered that this is only happening on my work laptop, not on my work desktop or home laptop, even though they all have the same version of windows and version of chrome installed. if you can't recreate this, it may just be an issue with my computer.

**Comment by noppa** [comment]
Unfortunately I haven't been able to repro this, the font works fine on my Windows & Linux. What's especially surprising to me here is that it's happening both in Chrome & Ff, which suggests that they are delegating the font rendering to host OS. I was under the impression that Chrome & Ff would not do that but ship with their own font rendering implementation.

If this causes problems in your own project, you could perhaps try setting the [letter-spacing](https://developer.mozilla.org/en-US/docs/Web/CSS/letter-spacing) property explicitly. Maybe that would help

**Comment by resims** [comment]
Thanks for the advice. I will be doing more research on my end, and until then, I feel this issue can be closed on your end. Thanks for the reply!
