### ISSUE TITLE
IE11 placeholder issue. When a placeholder is added in the input field, the placeholder text is also converted into bullets

### ISSUE THREAD

**Issue by prabodh44** [noppa/text-security#2]
The code works fine in chrome and safari though I have not tested it in mozilla. 

Code:
`		    				
				<md-input-container md-no-float>
					<label>Password</label> 
					  <input autocomplete="off" md-no-asterisk type = "text" name = "password"  required id = "passwordContainer" ng-model = 'password' style = "font-family:text-security-disc !important; font-size:10px !important;" placeholder="Enter password">
					  <div ng-messages = "loginform.password.$error">
						<div ng-message = "required">{{'label-loginfieldRequired'|translate}}</div> 
					</div>
				</md-input-container>`

this is my css for IE
`:-ms-input-placeholder{
    font-family: Montserrat !important;
    font-size: 12px !important;
    font-weight: 600 !important;
    font-style: normal !important;
    font-stretch: normal !important;
    line-height: 1.5 !important;
    letter-spacing: -0.1px !important;
    text-align: left !important;
    color: #838383 !important;
    text-transform: uppercase;
}`

			`

**Comment by noppa** [comment]
This doesn't seem like something that can be fixed from within this project.  
Apparently, IE and Edge don't allow changing the font for placeholders. 

Related: [Font size not working in placeholders on Microsoft Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11342294/).

¯\\\_(ツ)_/¯
