### ISSUE TITLE
if you copy and paste the password in another place it appears

### ISSUE THREAD

**Issue by MohamedElNady** [noppa/text-security#22]
if you copy the password and paste it in another place it appears

**Comment by noppa** [comment]
Yep, I'd file this under the readme's disclaimer
> Browsers might offer enhanced security features for password fields ... Opting to use a text field instead will leave your app out of these protections.

Browsers prevent copying password field texts, but there's nothing we can do in this font to do that for normal input fields. If this is an important feature for your use case, you may add more hacks to [modify the copied text with JavaScript](https://stackoverflow.com/a/4777746/6184698). So something like

```javascript
Array.from(document.getElementsByClassName('my-input'), el => 
  el.addEventListener('copy', (event) => {
    // Clear the copied content
    event.clipboardData.setData('text', '');
    event.preventDefault();
  }));

```

this should work in modern browsers at least.

**Comment by MohamedElNady** [comment]
yeah it works fine with me!

**Comment by varenc** [comment]
@MohamedElNady, this is totally unsolicited advice, but why are you trying to prevent a user from copying the text field? If it's just to appease someone that's one thing, but if it's for actual security, I don't think just overwriting the user's pasteboard is sufficient. It's easy for a user tell their browser to disable a site's access to the clipboard which would prevent the overwrite.  Also besides disallowing copying, real password fields have other features like being treated as a secure input which, depending on the operating system, protects them at a deeper level from things like keyboard loggers and anything malicious with screen reader access. I would take the [repo's security disclaimer](https://github.com/noppa/text-security#disclaimer) to heart and consider if this is really the right solution! \</end-of-unsolicted-advice>
